---
title: '2.3 Hands-On: Voting'
author: "Marco Wähner"
date: '2022-03-25'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Aufgabenstellung
Erstellen Sie einen Plot für die "Sonntagsfrage zur Bundestagswahl" (Variable pv01).


## Aufgabe 1
Importieren Sie die Daten aus dem ALLBUS 2018 und aktivieren Sie die notwendigen Packages

## Aufgabe 2
Kopieren Sie die Variable zur Sonntagsfrage in die neue Variable `vote`. Nicht-Wähler*innen erhalten ein Missing Value. Die Werte der ursprünglichen Variable sollen rekodiert werden in die Namen der Parteien (1 = Union, 2 = SPD etc.). Die neue Variable hat anschließend die Klasse `factor`.

## Aufgabe 3
* Erstellen Sie eine Häufigkeitsauszählung (absolut) mittels `barplot`. Es sollen keine Missing Values geplottet werden. Dies kann mit dem Befehl `drop_na(vote)` vor dem `ggplot`-Befehl unterdrückt werden.

* Erstellen Sie eine prozentuale Häufigkeitsauszählung  mittels `barplot`. Es sollen keine Missing Values geplottet werden. 

* Erstellen Sie eine prozentuale Häufigkeitsauszählung  mittels `barplot` getrennt für Ost- und Westdeutschland. Es sollen keine Missing Values geplottet werden. 

## Aufgabe 4
Wählen Sie einen Plot aus verändern Sie die Beschriftung und Darstellung, sodass der Plot abgedruckt werden könnte. Finden Sie eine Möglichkeit den Plot zu speichern/ zu exportieren.


